import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';
import { AnalysisResult } from '../types';

export const generateWordDoc = async (data: AnalysisResult) => {
    const doc = new Document({
        sections: [
            {
                properties: {},
                children: [
                    // Title
                    new Paragraph({
                        text: "Legal Lens AI - Contract Analysis Report",
                        heading: HeadingLevel.HEADING_1,
                        alignment: AlignmentType.CENTER,
                        spacing: { after: 300 },
                    }),

                    // Overview
                    new Paragraph({
                        text: "Executive Summary",
                        heading: HeadingLevel.HEADING_2,
                        spacing: { before: 200, after: 100 },
                    }),
                    new Paragraph({
                        children: [
                            new TextRun({
                                text: data.oneLineOverview || "No summary available.",
                                italics: true,
                            }),
                        ],
                        spacing: { after: 200 },
                    }),

                    // Verdict
                    new Paragraph({
                        text: "Verdict",
                        heading: HeadingLevel.HEADING_2,
                        spacing: { before: 200, after: 100 },
                    }),
                    new Paragraph({
                        text: `Risk Level: ${data.verdict}`,
                        spacing: { after: 200 },
                    }),

                    // Key Risks
                    new Paragraph({
                        text: "Identified Risks",
                        heading: HeadingLevel.HEADING_2,
                        spacing: { before: 200, after: 100 },
                    }),
                    ...data.risks.map((risk) => [
                        new Paragraph({
                            text: `• ${risk.level.toUpperCase()} RISK:`,
                            heading: HeadingLevel.HEADING_3,
                            spacing: { before: 100 },
                        }),
                        new Paragraph({
                            text: risk.description,
                            spacing: { after: 100 },
                        }),
                    ]).flat(),

                    // Financials
                    new Paragraph({
                        text: "Financials & Exit",
                        heading: HeadingLevel.HEADING_2,
                        spacing: { before: 200, after: 100 },
                    }),
                    new Paragraph({
                        text: data.moneyAndExit || "No financial details extracted.",
                        spacing: { after: 200 },
                    }),

                    // Footer
                    new Paragraph({
                        text: `Generated by Legal Lens AI on ${new Date().toLocaleDateString()}`,
                        alignment: AlignmentType.CENTER,
                        spacing: { before: 500 },
                    }),
                ],
            },
        ],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, `LegalLens-Report-${Date.now()}.docx`);
};
